NOTE_ONSET_SYMBOL = 1
NOTE_CONTINUED_SYMBOL = 2
NOTE_END_SYMBOL = 3

SAMPLE_RATE = 22050

LOWEST_NOTE_OFFSET = 20 + 1 # 20 is A0 in pretty_midi, and the extra 1 is for the indexing offset
CQT_NUM_BUCKETS = 88
MIN_NOTE_INTERVAL = 0.1
CQT_STEP_SIZE = 512

TIME_STEP_LENGTH = 16